services:
  - type: web
    name: bakers-lovers
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bakers-lovers-db
          property: connectionString
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: ADMIN_EMAIL
        value: admin@bakerslovers.com

databases:
  - name: bakers-lovers-db
    databaseName: bakerslovers
    user: bakerslovers
    plan: free